gerenciamentocontas/config/routes.rb
Rails.application.routes.draw do
  resources :expensetypes
  resources :expenses
  resources :accounts
  #get 'account/index'
  root 'accounts#index'
  resources :accounttypes
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

gerenciamentocontas/app/controllers/accounttypes_controller.rb
class AccounttypesController < ApplicationController
  before_action :set_accounttype, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /accounttypes
  # GET /accounttypes.json
  def index
    @accounttypes = Accounttype.all
  end

  # GET /accounttypes/1
  # GET /accounttypes/1.json
  def show
  end

  # GET /accounttypes/new
  def new
    @accounttype = Accounttype.new
  end

  # GET /accounttypes/1/edit
  def edit
  end

  # POST /accounttypes
  # POST /accounttypes.json
  def create
    @accounttype = Accounttype.new(accounttype_params)

    respond_to do |format|
      if @accounttype.save
        format.html { redirect_to @accounttype, notice: 'Accounttype was successfully created.' }
        format.json { render :show, status: :created, location: @accounttype }
      else
        format.html { render :new }
        format.json { render json: @accounttype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounttypes/1
  # PATCH/PUT /accounttypes/1.json
  def update
    respond_to do |format|
      if @accounttype.update(accounttype_params)
        format.html { redirect_to @accounttype, notice: 'Accounttype was successfully updated.' }
        format.json { render :show, status: :ok, location: @accounttype }
      else
        format.html { render :edit }
        format.json { render json: @accounttype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounttypes/1
  # DELETE /accounttypes/1.json
  def destroy
    @accounttype.destroy
    respond_to do |format|
      format.html { redirect_to accounttypes_url, notice: 'Accounttype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounttype
      @accounttype = Accounttype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def accounttype_params
      params.require(:accounttype).permit(:tipo_conta)
    end
end

gerenciamentocontas/app/helpers/accounttypes_helper.rb
module AccounttypesHelper
end

gerenciamentocontas/app/views/accounttypes/_form.html.erb
<%= form_with(model: accounttype, local: true) do |form| %>
  <% if accounttype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accounttype.errors.count, "error") %> prohibited this accounttype from being saved:</h2>

      <ul>
        <% accounttype.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo_conta %>
    <%= form.text_field :tipo_conta %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar" %>
  </div>
<% end %>

gerenciamentocontas/app/views/accounttypes/edit.html.erb
<h1>Editar Tipo de Conta</h1>

<%= render 'form', accounttype: @accounttype %>

<%= link_to 'Ver', @accounttype %> |
<%= link_to 'Voltar', accounttypes_path %>

gerenciamentocontas/app/views/accounttypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos de Conta</h1>

<table>
  <thead>
    <tr>
      <th>Tipo conta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounttypes.each do |accounttype| %>
      <tr>
        <td><%= accounttype.tipo_conta %></td>
        <td><%= link_to 'Ver', accounttype %></td>
        <td><%= link_to 'Editar', edit_accounttype_path(accounttype) %></td>
        <td><%= link_to 'Deletar', accounttype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Tipo de Conta', new_accounttype_path %>
<br>
<%= link_to 'Contas', accounts_path %>

gerenciamentocontas/app/views/accounttypes/new.html.erb
<h1>Novo Tipo de Conta</h1>

<%= render 'form', accounttype: @accounttype %>

<%= link_to 'Voltar', accounttypes_path %>

gerenciamentocontas/app/views/accounttypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo conta:</strong>
  <%= @accounttype.tipo_conta %>
</p>

<%= link_to 'Editar', edit_accounttype_path(@accounttype) %> |
<%= link_to 'Voltar', accounttypes_path %>