gerenciamentolivros/config/routes.rb
Rails.application.routes.draw do
  resources :reads
  resources :books do
    member do
      get 'informacao_livro'
      get 'leituras'
    end
  end
  resources :authors do
    member do
      get 'adicionar_livro'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

gerenciamentolivros/app/models/author.rb
class Author < ApplicationRecord
    belongs_to :book, optional: true
end

gerenciamentolivros/app/models/book.rb
class Book < ApplicationRecord
    searchkick
    has_many :author
    has_one :read

    def to_s
        nome_livro
    end
end

gerenciamentolivros/app/models/read.rb
class Read < ApplicationRecord
    has_one :book
end

gerenciamentolivros/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  def adicionar_livro
    @author = Author.find(params[:id])
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:nome, :book_id)
    end
end

gerenciamentolivros/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    if params[:search]
      @books = Book.where("nome_livro like '%#{params[:search]}%'")
    else
      @books = Book.all
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  def informacao_livro
    
    @book = Book.find(params[:id])
    @authors = Author.where(book_id: @book.id)
    @total_leituras = Read.where(book_id: @book.id).pluck('SUM(qtd_lido)')

  end

  def leituras
    @book = Book.find(params[:id])
    @read = Read.where(book_id: @book.id)
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:nome_livro, :status)
    end
end

gerenciamentolivros/app/controllers/reads_controller.rb
class ReadsController < ApplicationController
  before_action :set_read, only: [:show, :edit, :update, :destroy]

  # GET /reads
  # GET /reads.json
  def index
    @reads = Read.all
  end

  # GET /reads/1
  # GET /reads/1.json
  def show
  end

  # GET /reads/new
  def new
    @read = Read.new
  end

  # GET /reads/1/edit
  def edit
  end

  # POST /reads
  # POST /reads.json
  def create
    @read = Read.new(read_params)

    respond_to do |format|
      if @read.save
        format.html { redirect_to @read, notice: 'Read was successfully created.' }
        format.json { render :show, status: :created, location: @read }
      else
        format.html { render :new }
        format.json { render json: @read.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reads/1
  # PATCH/PUT /reads/1.json
  def update
    respond_to do |format|
      if @read.update(read_params)
        format.html { redirect_to @read, notice: 'Read was successfully updated.' }
        format.json { render :show, status: :ok, location: @read }
      else
        format.html { render :edit }
        format.json { render json: @read.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reads/1
  # DELETE /reads/1.json
  def destroy
    @read.destroy
    respond_to do |format|
      format.html { redirect_to reads_url, notice: 'Read was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_read
      @read = Read.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def read_params
      params.require(:read).permit(:data_leitura, :qtd_lido, :book_id)
    end
end

gerenciamentolivros/app/helpers/authors_helper.rb
module AuthorsHelper
end

gerenciamentolivros/app/helpers/books_helper.rb
module BooksHelper
end

gerenciamentolivros/app/helpers/reads_helper.rb
module ReadsHelper
end

gerenciamentolivros/app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
        <% author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.collection_select(:book_id,Book.all,:id,:nome_livro,include_blank: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gerenciamentolivros/app/views/authors/adicionar_livro.html.erb
<h1>Author: <%= @author.nome %> </h1>
<br>
<h1>Livro: <%= @author.book %> </h1>

gerenciamentolivros/app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

gerenciamentolivros/app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Nome do Autor</th>
      <th>Livro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.nome %></td>
        <td><%= author.book.nome_livro %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

gerenciamentolivros/app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

gerenciamentolivros/app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @author.nome %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

gerenciamentolivros/app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome_livro %>
    <%= form.text_field :nome_livro %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gerenciamentolivros/app/views/books/autores_livro.html.erb
<h1>Nome dos Autores do Livro: <%= @book.nome_livro%> </h1>



<div>

<% @authors.each do |author| %>
<tr>
        <td><%= author.nome %></td>
</tr>
<% end %>
</div>

<div>
<h2>Quantidade total de páginas lidas: <%= @total_leituras %></h2>
</div>

<br>

gerenciamentolivros/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

gerenciamentolivros/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<div>
<%= form_tag(books_path, :method => :get) do %>

   <%= text_field_tag 'search', nil, placeholder: "Entre com o nome de um livro..." %>
   <%= submit_tag  "Search"%>
<% end %>
</div>

<br>

<table>
  <thead>
    <tr>
      <th>Nome livro</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.nome_livro %></td>
        <td><%= book.status %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

gerenciamentolivros/app/views/books/informacao_livro_livro.html.erb
<h1>Nome dos Autores do Livro: <%= @book.nome_livro%> </h1>



<div>

<% @authors.each do |author| %>
<tr>
        <td><%= author.nome %></td>
</tr>
<% end %>
</div>

<div>
<h2>Quantidade total de páginas lidas: <%= @total_leituras %></h2>
</div>

<br>

gerenciamentolivros/app/views/books/leituras.html.erb
<h1>Leituras do Livro: <%= @book.nome_livro%> </h1>

<tbody>
    <% @read.each do |r| %>
      <tr>
        <td>Data da Leitura: <%= r.data_leitura %></td>
        <td>Quantidade lida: <%= r.qtd_lido %></td>
       <br>
      </tr>
    <% end %>
  </tbody>

gerenciamentolivros/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

gerenciamentolivros/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome livro:</strong>
  <%= @book.nome_livro %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

gerenciamentolivros/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerenciamentolivros</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

gerenciamentolivros/app/views/reads/_form.html.erb
<%= form_with(model: read, local: true) do |form| %>
  <% if read.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(read.errors.count, "error") %> prohibited this read from being saved:</h2>

      <ul>
        <% read.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data_leitura %>
    <%= form.date_select :data_leitura %>
  </div>

  <div class="field">
    <%= form.label :qtd_lido %>
    <%= form.number_field :qtd_lido %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.collection_select(:book_id,Book.all,:id,:nome_livro,include_blank: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

gerenciamentolivros/app/views/reads/edit.html.erb
<h1>Editing Read</h1>

<%= render 'form', read: @read %>

<%= link_to 'Show', @read %> |
<%= link_to 'Back', reads_path %>

gerenciamentolivros/app/views/reads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reads</h1>

<table>
  <thead>
    <tr>
      <th>Data leitura</th>
      <th>Qtd lido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reads.each do |read| %>
      <tr>
        <td><%= read.data_leitura %></td>
        <td><%= read.qtd_lido %></td>
        <td><%= link_to 'Show', read %></td>
        <td><%= link_to 'Edit', edit_read_path(read) %></td>
        <td><%= link_to 'Destroy', read, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Read', new_read_path %>

gerenciamentolivros/app/views/reads/new.html.erb
<h1>New Read</h1>

<%= render 'form', read: @read %>

<%= link_to 'Back', reads_path %>

gerenciamentolivros/app/views/reads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data leitura:</strong>
  <%= @read.data_leitura %>
</p>

<p>
  <strong>Qtd lido:</strong>
  <%= @read.qtd_lido %>
</p>

<%= link_to 'Edit', edit_read_path(@read) %> |
<%= link_to 'Back', reads_path %>