gerenciamentocontas/config/routes.rb
Rails.application.routes.draw do
  resources :expensetypes
  resources :expenses
  resources :accounts
  #get 'account/index'
  root 'accounts#index'
  resources :accounttypes
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

gerenciamentocontas/app/models/account.rb
class Account < ApplicationRecord
    belongs_to :accounttypes, optional: true
    belongs_to :users, optional: true
end

gerenciamentocontas/app/models/accounttype.rb
class Accounttype < ApplicationRecord
    has_many :accounts

    def to_s
        self.tipo_conta
    end
end

gerenciamentocontas/app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /accounts
  # GET /accounts.json
  def index
    @data_inicio = params[:data_inicio]
    @data_fim = params[:data_final]
    @saldo_datas = 0
    if @data_inicio == "" and @data_fim == ""
      @accounts = Account.where(user_id: current_user.id)
    elsif @data_inicio and @data_fim
      @accounts = Account.where(user_id: current_user.id,:data_conta => @data_inicio..@data_fim)
      @total_contas_mes = Account.where(user_id: current_user.id,:data_conta => @data_inicio..@data_fim).pluck('SUM(qtd)')[0]
      @total_receitas_data = Expense.where(user_id: current_user.id,:data => @data_inicio..@data_fim).pluck('SUM(quantidade)')[0]
      if @total_contas_mes.present? and @total_receitas_data.present?
        @saldo_datas = @total_receitas_data - @total_contas_mes
      end
    else
      @accounts = Account.where(user_id: current_user.id)
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:qtd, :data_conta, :comentario,:accounttype_id)
    end
end

gerenciamentocontas/app/helpers/accounts_helper.rb
module AccountsHelper
end

gerenciamentocontas/app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Quantidade %>
    <%= form.text_field :qtd %>
  </div>

  <div class="field">
    <%= form.label :Data_conta %>
    <%= form.date_select :data_conta %>
  </div>

  <div class="field">
    <%= form.label :Comentario %>
    <%= form.text_field :comentario %>
  </div>

  <div class="field">
    <%= form.label :Conta %>
    <%= form.collection_select(:accounttype_id,Accounttype.all,:id,:tipo_conta,include_blank: false) %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar" %>
  </div>
<% end %>

gerenciamentocontas/app/views/accounts/edit.html.erb
<h1>Editar Conta</h1>

<%= render 'form', account: @account %>

<%= link_to 'Ver', @account %> |
<%= link_to 'Voltar', accounts_path %>

gerenciamentocontas/app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contas</h1>

<div>
<%= form_tag(accounts_path, :method => :get) do %>

   <%= date_field_tag 'data_inicio', nil, placeholder: "Data inicial" %>
   <%= date_field_tag 'data_final', nil, placeholder: "Data inicial" %>
   <%= submit_tag  "Pesquisa"%>
<% end %>


</div>



<table>
  <thead>
    <tr>
      <th>Quantidade</th>
      <th>Data conta</th>
      <th>Comentario</th>
      <th>Usuário</th>
      <th>Tipo de Conta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.qtd %></td>
        <td><%= account.data_conta %></td>
        <td><%= account.comentario %></td>
        <td><%= current_user.email %></td>
        <td><%= Accounttype.find(account.accounttype_id) %></td>
        <td><%= link_to 'Ver', account %></td>
        <td><%= link_to 'Editar', edit_account_path(account) %></td>
        <td><%= link_to 'Deletar', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div>
<% if @total_contas_mes == 0%>

<% elsif @total_contas_mes > 0%>
<p>Total gasto: <%= @total_contas_mes %> reais</p>

<% end %>
</div>

<br>

<% if @saldo_datas == 0%>

<% elsif @saldo_datas < 0 %>
<p> O saldo é <%= @saldo_datas.round(2) %> negativo </p>

<% elsif @saldo_datas >= 0 %>
<p> O saldo é <%= @saldo_datas.round(2) %> positivo </p>
<% end %>

<br>

<%= link_to 'Nova Conta', new_account_path %>
<br>
<%= link_to 'Tipos de Conta', accounttypes_path %>
<br>
<%= link_to 'Receitas', expenses_path %>

gerenciamentocontas/app/views/accounts/new.html.erb
<h1>Nova Conta</h1>

<%= render 'form', account: @account %>

<%= link_to 'Voltar', accounts_path %>

gerenciamentocontas/app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Qtd:</strong>
  <%= @account.qtd %>
</p>

<p>
  <strong>Data conta:</strong>
  <%= @account.data_conta %>
</p>

<p>
  <strong>Comentario:</strong>
  <%= @account.comentario %>
</p>

<%= link_to 'Editar', edit_account_path(@account) %> |
<%= link_to 'Voltar', accounts_path %>