gerenciamentocontas/config/routes.rb
Rails.application.routes.draw do
  resources :expensetypes
  resources :expenses
  resources :accounts
  #get 'account/index'
  root 'accounts#index'
  resources :accounttypes
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

gerenciamentocontas/app/controllers/expensetypes_controller.rb
class ExpensetypesController < ApplicationController
  before_action :set_expensetype, only: [:show, :edit, :update, :destroy]

  # GET /expensetypes
  # GET /expensetypes.json
  def index
    @expensetypes = Expensetype.all
  end

  # GET /expensetypes/1
  # GET /expensetypes/1.json
  def show
  end

  # GET /expensetypes/new
  def new
    @expensetype = Expensetype.new
  end

  # GET /expensetypes/1/edit
  def edit
  end

  # POST /expensetypes
  # POST /expensetypes.json
  def create
    @expensetype = Expensetype.new(expensetype_params)

    respond_to do |format|
      if @expensetype.save
        format.html { redirect_to @expensetype, notice: 'Expensetype was successfully created.' }
        format.json { render :show, status: :created, location: @expensetype }
      else
        format.html { render :new }
        format.json { render json: @expensetype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expensetypes/1
  # PATCH/PUT /expensetypes/1.json
  def update
    respond_to do |format|
      if @expensetype.update(expensetype_params)
        format.html { redirect_to @expensetype, notice: 'Expensetype was successfully updated.' }
        format.json { render :show, status: :ok, location: @expensetype }
      else
        format.html { render :edit }
        format.json { render json: @expensetype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expensetypes/1
  # DELETE /expensetypes/1.json
  def destroy
    @expensetype.destroy
    respond_to do |format|
      format.html { redirect_to expensetypes_url, notice: 'Expensetype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expensetype
      @expensetype = Expensetype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expensetype_params
      params.require(:expensetype).permit(:tipo_receita)
    end
end

gerenciamentocontas/app/helpers/expensetypes_helper.rb
module ExpensetypesHelper
end

gerenciamentocontas/app/views/expensetypes/_form.html.erb
<%= form_with(model: expensetype, local: true) do |form| %>
  <% if expensetype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expensetype.errors.count, "error") %> prohibited this expensetype from being saved:</h2>

      <ul>
        <% expensetype.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tipo_receita %>
    <%= form.text_field :tipo_receita %>
  </div>

  <div class="actions">
  <%= form.submit "Enviar" %>
  </div>
<% end %>

gerenciamentocontas/app/views/expensetypes/edit.html.erb
<h1>Editar Tipo de Receita</h1>

<%= render 'form', expensetype: @expensetype %>

<%= link_to 'Ver', @expensetype %> |
<%= link_to 'Voltar', expensetypes_path %>

gerenciamentocontas/app/views/expensetypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipos de Receita</h1>

<table>
  <thead>
    <tr>
      <th>Tipo receita</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expensetypes.each do |expensetype| %>
      <tr>
        <td><%= expensetype.tipo_receita %></td>
        <td><%= link_to 'Ver', expensetype %></td>
        <td><%= link_to 'Editar', edit_expensetype_path(expensetype) %></td>
        <td><%= link_to 'Deletar', expensetype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Cadastrar Nova Receita', new_expensetype_path %>

gerenciamentocontas/app/views/expensetypes/new.html.erb
<h1>Novo Tipo de Receita</h1>

<%= render 'form', expensetype: @expensetype %>

<%= link_to 'Voltar', expensetypes_path %>

gerenciamentocontas/app/views/expensetypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo receita:</strong>
  <%= @expensetype.tipo_receita %>
</p>

<%= link_to 'Editar', edit_expensetype_path(@expensetype) %> |
<%= link_to 'Voltar', expensetypes_path %>